Debug: false
Language: Chinese
Sound:
  Action:
    Start: ENTITY_ARROW_HIT_PLAYER
    Success: ENTITY_VILLAGER_YES
    Failure: BLOCK_ANVIL_DESTROY
  Vote:
    Start: ENTITY_VILLAGER_YES
    End: BLOCK_ANVIL_HIT