name: VoteUp
version: ${project.version}
main: net.shoal.sir.voteup.VoteUp
api-version: 1.13
authors: [EntityParrot_]
commands:
  voteup:
    aliases:
      - vote
      - votes
permissions:
  VoteUp.*:
    description: All access for VoteUp plugin.
    default: op
    children:
      VoteUp.vote.*: true
      VoteUp.create.*: true
      VoteUp.notice: true
  VoteUp.notice:
    description: Allows you get the notications when loggin.
    default: op
  VoteUp.user:
    description: Quickly configure basic VoteUp permissions.
    default: true
    children:
      VoteUp.vote.*: true
      VoteUp.create.simple: true
  VoteUp.vote.*:
    description: Allows you to vote.
    default: true
    children:
      VoteUp.vote.accept: true
      VoteUp.vote.neutral: true
      VoteUp.vote.refuse: true
  VoteUp.vote.accept:
    description: Allows you to vote as ACCEPT.
    default: true
  VoteUp.vote.neutral:
    description: Allows you to vote as NEUTRAL.
    default: true
  VoteUp.vote.refuse:
    description: Allows you to vote as REFUSE.
    default: true
  VoteUp.create.simple:
    description: Quickly configure basic voting creation permissions.
    default: true
    children:
      VoteUp.create.title: true
      VoteUp.create.description: true
      VoteUp.create.duration: true
  VoteUp.create.*:
    description: Allows you to create & start a vote.
    default: op
    children:
      VoteUp.create.title: true
      VoteUp.create.type: true
      VoteUp.create.amount: true
      VoteUp.create.description: true
      VoteUp.create.duration: true
      VoteUp.create.choice: true
      VoteUp.create.autocast: true
      VoteUp.create.result: true
  VoteUp.create.title:
    description: Allows you to modify the vote's title during the creating.
    default: op
  VoteUp.create.type:
    description: Allows you to modify the vote's type during the creating.
    default: op
  VoteUp.create.amount:
    description: Allows you to modify the vote's goal of accpet player's amount during the creating.
    default: op
  VoteUp.create.description:
    description: Allows you to modify the vote's description content during the creating.
    default: op
  VoteUp.create.duration:
    description: Allows you to modify the vote's duration during the creating.
    default: op
  VoteUp.create.choice:
    description: Allows you to modify the vote's choice's display content during the creating.
    default: op
  VoteUp.create.autocast:
    description: Allows you to modify the vote's autocast content during the creating.
    default: op
  VoteUp.create.result:
    description: Allows you to modify the vote's result's content during the creating.
    default: op

