Debug: false
bStats: true
Language: Chinese
Sound:
  Enable: true
  Action:
    Start: ENTITY_ARROW_HIT_PLAYER
    Success: ENTITY_VILLAGER_YES
    Failure: BLOCK_ANVIL_DESTROY
  Vote:
    Start: ENTITY_ARROW_HIT_PLAYER
    End: BLOCK_ANVIL_HIT
Settings:
  ParticipantLeast: 5
  Allow:
    Anonymous: true
    Public: true
    Edit:
      Vote: true
      Participant: true
  Broadcast:
    Title:
      VoteStart: true
      VoteEnd: false
      FadeIn: 5
      Stay: 10
      FadeOut: 7
Autocast:
  Enable: true
  Usermode: true
  Blacklist: false
  List:
    - 'op'
    - 'gamemode'
    - 'gm'
    - 'godmode'
    - 'give'
    - 'kill'
    - 'sudo'
Admin: []